### ISSUE TITLE
Import Error: cannot import name 'bitpack'

### ISSUE THREAD

**Issue by AwesomeGamer89** [Anjok07/ultimatevocalremovergui#189]
raceback (most recent call last):
  File "UVR.py", line 38, in <module>
    import inference_MDX
  File "/home/cole/github/UVR-V5.21/inference_MDX.py", line 17, in <module>
    from demucs.pretrained import get_model as _gm
  File "/home/cole/github/UVR-V5.21/demucs/pretrained.py", line 15, in <module>
    from .hdemucs import HDemucs
  File "/home/cole/github/UVR-V5.21/demucs/hdemucs.py", line 17, in <module>
    from .demucs import DConv, rescale_module
  File "/home/cole/github/UVR-V5.21/demucs/demucs.py", line 15, in <module>
    from .states import capture_init
  File "/home/cole/github/UVR-V5.21/demucs/states.py", line 19, in <module>
    from diffq import DiffQuantizer, UniformQuantizer, restore_quantized_state
  File "/home/cole/github/UVR-V5.21/diffq/__init__.py", line 22, in <module>
    from .uniform import UniformQuantizer
  File "/home/cole/github/UVR-V5.21/diffq/uniform.py", line 13, in <module>
    from .base import BaseQuantizer
  File "/home/cole/github/UVR-V5.21/diffq/base.py", line 21, in <module>
    from . import bitpack
ImportError: cannot import name 'bitpack' from partially initialized module 'diffq' (most likely due to a circular import) (/home/cole/github/UVR-V5.21/diffq/__init__.py)

got this after I updated to 5.3.0. On Linux Mint 20.2

**Comment by greendrake** [comment]
+1

It looks like the code was authored on Windows as there is this binary file [bitpack.cp39-win_amd64.pyd
](https://github.com/Anjok07/ultimatevocalremovergui/blob/master/diffq/bitpack.cp39-win_amd64.pyd) which apparently serves the import on Windows.

The original `diffq` uses the module in PYX format: [bitpack.pyx](https://github.com/facebookresearch/diffq/blob/main/bitpack.pyx). Not too sure how to import it on Linux. [This](https://stackoverflow.com/questions/7508803/how-do-i-import-function-from-pyx-file-in-python) might be the way but I haven't tried it yet.

**Comment by greendrake** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/pull/213 fixes it.

**Comment by AwesomeGamer89** [comment]
> #213 fixes it (assuming Cython is installed).

tried using the fix with cython, now I have a "No modules named 'win32api'" error. Can't seem to install pywin32 either.

**Comment by greendrake** [comment]
> tried using the fix with cython, now I have a "No modules named 'win32api'" error. Can't seem to install pywin32 either.

I tested it on Linux only, so maybe it needs some further tweaking to work on Windows.

**Comment by AwesomeGamer89** [comment]
> > tried using the fix with cython, now I have a "No modules named 'win32api'" error. Can't seem to install pywin32 either.
> 
> I tested it on Linux only, so maybe it needs some further tweaking to work on Windows.

I'm currently on Linux mint 20.2, so It's weird that it doesn't work.

**Comment by greendrake** [comment]
> I'm currently on Linux mint 20.2

Then nothing should be requiring any sort of "*win32*" things. Guess you just need to find what tries to link them and comment out.

**Comment by AwesomeGamer89** [comment]
> > I'm currently on Linux mint 20.2
> 
> Then nothing should be requiring any sort of "*win32*" things. Guess you just need to find what tries to link them and comment out.

Still not fixed on latest version. Maybe If you update your repo I could try it again?

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link: https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.5.0
